apiVersion: v1
kind: Service
metadata:
  name: rnode-immersion
  labels:
    app: rnode
spec:
  ports:
    - protocol: TCP
      port: 5401
      targetPort: 5401
  selector:
    app: rnode
    tier: blockchain
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rnode-claim
  labels:
    app: rnode
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: rnode-immersion
  labels:
    app: rnode
spec:
  selector:
    matchLabels:
      app: rnode
      tier: blockchain
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rnode
        tier: blockchain
    spec:
      containers:
      - image: kayvank/rnode:0.6.1
        name: rnode
        ports:
        - containerPort: 5401
          name: grpc
        volumeMounts:
        - name: pv-rnode-storage
          mountPath: /var/lib
      volumes:
      - name: pv-rnode-storage
        persistentVolumeClaim:
          claimName: pvc-rnode-claim
