---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: rsong-rchain-coop
spec:
  secretName: tls-letsencrypt-rsong
  commonName: rsong-rchain-coop
  dnsNames:
    - rsong-admin.rchain.coop
    - www.rsong-admin.rchain.coop
    - rsong-proxy.rchain.coop
    - www.rsong-proxy.rchain.coop

  issuerRef:
    name: rsong-rchain-coop
    kind: ClusterIssuer
  acme:
    config:
      - ingressClass: nginx
        domains:
          - rsong-admin.rchain.coop
          - www.rsong-admin.rchain.coop
          - rsong-proxy.rchain.coop
          - www.rsong-proxy.rchain.coop



