apiVersion: v1
kind: Pod
metadata:
  name: immersion-rc-proxy
  labels:
    purpose: rchain-immersion-proxy
    env: prd
spec:
  containers:
  - name: immersion-rc-proxy-container
    image: kayvank/immersion-rc-proxy:1.2-SNAPSHOT-berlin-demo
    resources:
      limits:
        cpu: "8000m"
        memory: "10G"
      requests:
        cpu: "4000m"
        memory: "5G"
    env:
    - name: HTTP_PORT
      value: "9000"
    - name: AUTH_NAME
      value: "immersion"
    - name: AUTH_PASSWORD
      value: "immersion-password"
    - name: API_VERSION
      value: "v1"
    - name: GRPC_SERVER
      value: "34.222.16.129"
    - name: GRPC_PORT
      value: "40401"

